name: This is a github action
run-name: this is the run name
on: [push]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: test
          uses: actions/setup-node@v4
          with:
            node-version: '20.11.0'
        - run: sleep 3s && echo test
    
